services:
  ${DOMAIN_ESCAPED}_mumble:
    container_name: ${DOMAIN_ESCAPED}_mumble
    image: mumblevoip/mumble-server:latest
    hostname: ${DOMAIN_ESCAPED}
    restart: on-failure
    ports:
        - 64738:64738
        - 64738:64738/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.${DOMAIN_ESCAPED}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${DOMAIN_ESCAPED}.tls.certresolver=LetsEncrypt

networks:
  ${DOMAIN_ESCAPED}:
  proxy:
    name: proxy
    external: true
