# docker-compose file for a php MysqlWebserver installation
services:
  ${DOMAIN_ESCAPED}_db:
    container_name: ${DOMAIN_ESCAPED}_mysql
    environment:
      MYSQL_DATABASE: php
      MYSQL_USER: php
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    image: mysql:5.7
    networks:
      - ${DOMAIN_ESCAPED}
    restart: always
    volumes:
      - ${DOMAIN_PATH}/mysql:/var/lib/mysql

  ${DOMAIN_ESCAPED}_php:
    container_name: ${DOMAIN_ESCAPED}_php
    depends_on:
      - ${DOMAIN_ESCAPED}_db
    environment:
      WORDPRESS_DB_HOST: ${DOMAIN_ESCAPED}_db:3306
      WORDPRESS_DB_USER: php
      WORDPRESS_DB_NAME: php
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    image: sohmc/php-mysqli:8-apache
    networks:
      - ${DOMAIN_ESCAPED}
      - proxy
    restart: always
    volumes:
      - ${DOMAIN_PATH}/php:/var/www/html
      - ${DOMAIN_PATH}/php.ini:/usr/local/etc/php/conf.d/external.ini
    labels:
      - traefik.enable=true
      - traefik.http.routers.${DOMAIN_ESCAPED}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${DOMAIN_ESCAPED}.tls.certresolver=LetsEncrypt

networks:
  ${DOMAIN_ESCAPED}:
  proxy:
    name: proxy
    external: true
