# docker-compose file for a Nextcloud installation

version: '3.5'

services:
    ${DOMAIN_ESCAPED}_db:
      container_name: ${DOMAIN_ESCAPED}_mysql
      environment:
        MYSQL_DATABASE: nextcloud
        MYSQL_USER: nextcloud
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      image: mysql:5.7
      networks:
        - ${DOMAIN_ESCAPED}
      restart: always
      volumes:
        - ${DOMAIN_PATH}/mysql:/var/lib/mysql

    ${DOMAIN_ESCAPED}_nextcloud:
      container_name: ${DOMAIN_ESCAPED}_nextcloud
      depends_on:
        - ${DOMAIN_ESCAPED}_db
        - ${DOMAIN_ESCAPED}_redis
      environment:
        MYSQL_HOST: ${DOMAIN_ESCAPED}_db:3306
        MYSQL_USER: nextcloud
        MYSQL_DATABASE: nextcloud
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        NEXTCLOUD_DATA_DIR: /var/www/html/data
        NEXTCLOUD_TRUSTED_DOMAINS: ${DOMAIN}
        NEXTCLOUD_ADMIN_USER: admin
        NEXTCLOUD_ADMIN_PASSWORD: admin
        REDIS_HOST: ${DOMAIN_ESCAPED}_redis
        #REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      image: nextcloud:latest
      networks:
        - ${DOMAIN_ESCAPED}
      ports:
        - "${HTTP_PORT}:80"
      restart: always
      volumes:
        - ${DOMAIN_PATH}/nextcloud:/var/www/html

    ${DOMAIN_ESCAPED}_redis:
      container_name: ${DOMAIN_ESCAPED}_redis
      #command: [
      #  "bash", "-c",
      #  '
      #  docker-entrypoint.sh
      #  --appendonly yes
      #  --requirepass "$$(cat $$HOST_PASSWORD)"
      #  '
      #]
      #environment:
      #  HOST_PASSWORD: ${REDIS_PASSWORD}
      expose:
        - "6379"
      image: redis:latest
      networks:
        - ${DOMAIN_ESCAPED}
      restart: always
      volumes:
        - ${DOMAIN_PATH}/redis/data:/data

networks:
    ${DOMAIN_ESCAPED}:
