# docker-compose file for a php Webserver installation
services:
  ${DOMAIN_ESCAPED}_php:
    container_name: ${DOMAIN_ESCAPED}_php
    image: sohmc/php-mysqli:8-apache
    networks:
      - ${DOMAIN_ESCAPED}
      - proxy
    restart: always
    volumes:
      - ${DOMAIN_PATH}/php:/var/www/html
      - ${DOMAIN_PATH}/php.ini:/usr/local/etc/php/conf.d/external.ini
    labels:
      - traefik.enable=true
      - traefik.http.routers.${DOMAIN_ESCAPED}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${DOMAIN_ESCAPED}.tls.certresolver=LetsEncrypt

networks:
  ${DOMAIN_ESCAPED}:
  proxy:
    name: proxy
    external: true
