# docker-compose file for a WordPress installation

version: '3.3'

services:
   db:
     container_name: ${DOMAIN}_mysql
     environment:
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     image: mysql:5.7
     restart: always
     volumes:
       - db:/var/lib/mysql

   wordpress:
     container_name: ${DOMAIN}_wordpress
     depends_on:
       - db
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
     image: wordpress:latest
     ports:
       - "${HTTP_PORT}:80"
     restart: always
     volumes:
       - wordpress:/var/www/html
volumes:
  db:
    driver: local
    driver_opts:
      device: ${DOMAIN_PATH}/mysql
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: ${DOMAIN_PATH}/wordpress
      o: bind
      type: none
