# docker-compose file for a WordPress installation
name: service-manager
services:
  ${DOMAIN_ESCAPED}_db:
    container_name: ${DOMAIN_ESCAPED}_mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    image: mysql:5.7
    networks:
      - ${DOMAIN_ESCAPED}
    restart: always
    volumes:
      - ${DOMAIN_PATH}/mysql:/var/lib/mysql
  ${DOMAIN_ESCAPED}_wordpress:
    container_name: ${DOMAIN_ESCAPED}_wordpress
    depends_on:
      - ${DOMAIN_ESCAPED}_db
    environment:
      WORDPRESS_DB_HOST: ${DOMAIN_ESCAPED}_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    image: wordpress:latest
    networks:
      - ${DOMAIN_ESCAPED}
      - proxy
    ports:
      - "${HTTP_PORT}:80"
    restart: always
    volumes:
      - ${DOMAIN_PATH}/wordpress:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.${DOMAIN_ESCAPED}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${DOMAIN_ESCAPED}.entrypoints=websecure
      - traefik.http.routers.${DOMAIN_ESCAPED}.tls.certresolver=LetsEncrypt
networks:
  ${DOMAIN_ESCAPED}:
  proxy:
    name: proxy
